[package]
name = "rust-g"
version = "0.3.0"
authors = ["Bjorn Neergaard <bjorn@neersighted.com>"]

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
lto = true

[dependencies]
chrono = "0.4"
failure = "0.1"
libc = "0.2"
