[package]
name = "rust-g"
version = "0.1.1"
authors = ["Bjorn Neergaard <bjorn@neersighted.com>"]

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
lto = true

[dependencies]
chrono = "0.4"
libc = "0.2.0"
